import type { Wine, Movement, Stock, LowStockAlert, Location, StorageLot } from "./types"

// Mock Locations
export const mockLocations: Location[] = [
  { id: "1", name: "Main Warehouse", description: "Primary storage facility" },
  { id: "2", name: "Downtown Store", description: "Retail location in city center" },
  { id: "3", name: "Cellar Storage", description: "Temperature controlled cellar" },
]

// Mock Storage Lots
export const mockStorageLots: StorageLot[] = [
  { id: "1", name: "Section A", locationId: "1", locationName: "Main Warehouse", description: "Front section" },
  { id: "2", name: "Section B", locationId: "1", locationName: "Main Warehouse", description: "Back section" },
  { id: "3", name: "Showroom", locationId: "2", locationName: "Downtown Store", description: "Display area" },
  { id: "4", name: "Reserve Room", locationId: "2", locationName: "Downtown Store", description: "High-value wines" },
  { id: "5", name: "Aging Room", locationId: "3", locationName: "Cellar Storage", description: "For long-term aging" },
  {
    id: "6",
    name: "New Arrivals",
    locationId: "3",
    locationName: "Cellar Storage",
    description: "Recent acquisitions",
  },
]

// Mock Wines
export const mockWines: Wine[] = [
  {
    id: "1",
    product_code: "CHM-MRG-15",
    barcode: "3760095252021",
    wine_name: "Château Margaux",
    description: "Classic Bordeaux blend with notes of blackcurrant, cedar and graphite.",
    vintage_year: 2015,
    producer: "Château Margaux",
    country: "France",
    region: "Bordeaux",
    appellation: "Margaux AOC",
    grape_varieties: ["Cabernet Sauvignon", "Merlot", "Petit Verdot", "Cabernet Franc"],
    alcohol_content: 13.5,
    bottling_date: "2017-06-15",
    price_bottle: 950.0,
    price_glass: 190.0,
    cost_price: 750.0,
    totalQuantity: 24,
    createdAt: "2023-01-15T12:00:00Z",
    updatedAt: "2023-06-10T14:30:00Z",
  },
  {
    id: "2",
    product_code: "OPS-ONE-18",
    barcode: "089819003143",
    wine_name: "Opus One",
    description: "Bordeaux-style blend with rich cassis, blackberry and subtle oak influence.",
    vintage_year: 2018,
    producer: "Opus One Winery",
    country: "USA",
    region: "Napa Valley",
    appellation: "Oakville AVA",
    grape_varieties: ["Cabernet Sauvignon", "Merlot", "Cabernet Franc", "Petit Verdot", "Malbec"],
    alcohol_content: 14.2,
    bottling_date: "2020-08-10",
    price_bottle: 450.0,
    price_glass: 90.0,
    cost_price: 350.0,
    totalQuantity: 18,
    createdAt: "2023-02-20T10:15:00Z",
    updatedAt: "2023-07-05T09:45:00Z",
  },
  {
    id: "3",
    product_code: "PNF-GRG-17",
    wine_name: "Penfolds Grange",
    description: "Powerful Shiraz with concentrated dark fruit and spice notes.",
    vintage_year: 2017,
    producer: "Penfolds",
    country: "Australia",
    region: "South Australia",
    appellation: "Multi-regional Blend",
    grape_varieties: ["Shiraz", "Cabernet Sauvignon"],
    alcohol_content: 14.5,
    price_bottle: 750.0,
    cost_price: 550.0,
    totalQuantity: 12,
    createdAt: "2023-03-10T16:30:00Z",
    updatedAt: "2023-08-12T11:20:00Z",
  },
  {
    id: "4",
    product_code: "SSC-TUS-19",
    barcode: "8032610313338",
    wine_name: "Sassicaia",
    description: "Super Tuscan with elegant structure, red fruits and herbal notes.",
    vintage_year: 2019,
    producer: "Tenuta San Guido",
    country: "Italy",
    region: "Tuscany",
    appellation: "Bolgheri Sassicaia DOC",
    grape_varieties: ["Cabernet Sauvignon", "Cabernet Franc"],
    alcohol_content: 13.8,
    bottling_date: "2021-05-20",
    price_bottle: 350.0,
    price_glass: 70.0,
    cost_price: 250.0,
    condition_notes: ["Damaged Label"],
    totalQuantity: 9,
    createdAt: "2023-04-05T14:20:00Z",
    updatedAt: "2023-09-18T15:10:00Z",
  },
  {
    id: "5",
    product_code: "SCR-EGL-16",
    wine_name: "Screaming Eagle",
    description: "Cult Cabernet with exceptional depth, complexity and aging potential.",
    vintage_year: 2016,
    producer: "Screaming Eagle",
    country: "USA",
    region: "Napa Valley",
    appellation: "Oakville AVA",
    grape_varieties: ["Cabernet Sauvignon", "Merlot", "Cabernet Franc"],
    alcohol_content: 14.8,
    price_bottle: 3500.0,
    cost_price: 2800.0,
    totalQuantity: 3,
    createdAt: "2023-05-15T09:40:00Z",
    updatedAt: "2023-10-22T13:25:00Z",
  },
  {
    id: "6",
    product_code: "DRC-ROM-18",
    wine_name: "Domaine de la Romanée-Conti",
    description: "World-renowned Pinot Noir with ethereal complexity and finesse.",
    vintage_year: 2018,
    producer: "Domaine de la Romanée-Conti",
    country: "France",
    region: "Burgundy",
    appellation: "Romanée-Conti Grand Cru",
    grape_varieties: ["Pinot Noir"],
    alcohol_content: 13.2,
    bottling_date: "2020-03-15",
    price_bottle: 15000.0,
    cost_price: 12000.0,
    totalQuantity: 4,
    createdAt: "2023-06-20T11:55:00Z",
    updatedAt: "2023-11-30T10:15:00Z",
  },
  {
    id: "7",
    product_code: "VGS-UNC-12",
    barcode: "8423355000032",
    wine_name: "Vega Sicilia Único",
    description: "Spain's most prestigious wine with remarkable power and elegance.",
    vintage_year: 2012,
    producer: "Vega Sicilia",
    country: "Spain",
    region: "Ribera del Duero",
    grape_varieties: ["Tempranillo", "Cabernet Sauvignon"],
    alcohol_content: 14.0,
    price_bottle: 550.0,
    price_glass: 110.0,
    cost_price: 400.0,
    totalQuantity: 8,
    createdAt: "2023-07-10T13:10:00Z",
    updatedAt: "2023-12-15T16:40:00Z",
  },
  {
    id: "8",
    product_code: "CHY-STR-17",
    wine_name: "Château d'Yquem",
    description: "Legendary sweet wine with honey, apricot and botrytis complexity.",
    vintage_year: 2017,
    producer: "Château d'Yquem",
    country: "France",
    region: "Sauternes",
    appellation: "Sauternes AOC",
    grape_varieties: ["Sémillon", "Sauvignon Blanc"],
    alcohol_content: 13.5,
    bottling_date: "2019-09-10",
    price_bottle: 450.0,
    price_glass: 90.0,
    cost_price: 320.0,
    condition_notes: ["Pristine"],
    totalQuantity: 15,
    createdAt: "2023-08-25T15:30:00Z",
    updatedAt: "2024-01-20T12:50:00Z",
  },
]

// Mock Stock Distribution
export const mockStocks: Stock[] = [
  {
    wineId: "1",
    locationId: "1",
    storageLotId: "1",
    locationName: "Main Warehouse",
    storageLotName: "Section A",
    quantity: 15,
  },
  {
    wineId: "1",
    locationId: "2",
    storageLotId: "3",
    locationName: "Downtown Store",
    storageLotName: "Showroom",
    quantity: 5,
  },
  {
    wineId: "1",
    locationId: "3",
    storageLotId: "5",
    locationName: "Cellar Storage",
    storageLotName: "Aging Room",
    quantity: 4,
  },

  {
    wineId: "2",
    locationId: "1",
    storageLotId: "1",
    locationName: "Main Warehouse",
    storageLotName: "Section A",
    quantity: 10,
  },
  {
    wineId: "2",
    locationId: "2",
    storageLotId: "4",
    locationName: "Downtown Store",
    storageLotName: "Reserve Room",
    quantity: 8,
  },

  {
    wineId: "3",
    locationId: "1",
    storageLotId: "2",
    locationName: "Main Warehouse",
    storageLotName: "Section B",
    quantity: 8,
  },
  {
    wineId: "3",
    locationId: "3",
    storageLotId: "5",
    locationName: "Cellar Storage",
    storageLotName: "Aging Room",
    quantity: 4,
  },

  {
    wineId: "4",
    locationId: "1",
    storageLotId: "2",
    locationName: "Main Warehouse",
    storageLotName: "Section B",
    quantity: 6,
  },
  {
    wineId: "4",
    locationId: "2",
    storageLotId: "3",
    locationName: "Downtown Store",
    storageLotName: "Showroom",
    quantity: 3,
  },

  {
    wineId: "5",
    locationId: "2",
    storageLotId: "4",
    locationName: "Downtown Store",
    storageLotName: "Reserve Room",
    quantity: 3,
  },

  {
    wineId: "6",
    locationId: "3",
    storageLotId: "5",
    locationName: "Cellar Storage",
    storageLotName: "Aging Room",
    quantity: 4,
  },

  {
    wineId: "7",
    locationId: "1",
    storageLotId: "1",
    locationName: "Main Warehouse",
    storageLotName: "Section A",
    quantity: 5,
  },
  {
    wineId: "7",
    locationId: "3",
    storageLotId: "6",
    locationName: "Cellar Storage",
    storageLotName: "New Arrivals",
    quantity: 3,
  },

  {
    wineId: "8",
    locationId: "1",
    storageLotId: "2",
    locationName: "Main Warehouse",
    storageLotName: "Section B",
    quantity: 10,
  },
  {
    wineId: "8",
    locationId: "2",
    storageLotId: "3",
    locationName: "Downtown Store",
    storageLotName: "Showroom",
    quantity: 5,
  },
]

// Mock Movements
export const mockMovements: Movement[] = [
  {
    id: "1",
    wineId: "1",
    wineName: "Château Margaux",
    vintage: 2015,
    type: "in",
    quantity: 20,
    toLocationId: "1",
    toLocationName: "Main Warehouse",
    toStorageLotId: "1",
    toStorageLotName: "Section A",
    userId: "1",
    userName: "Admin User",
    notes: "Initial stock",
    createdAt: "2023-06-01T09:30:00Z",
  },
  {
    id: "2",
    wineId: "1",
    wineName: "Château Margaux",
    vintage: 2015,
    type: "transfer",
    quantity: 5,
    fromLocationId: "1",
    fromLocationName: "Main Warehouse",
    fromStorageLotId: "1",
    fromStorageLotName: "Section A",
    toLocationId: "2",
    toLocationName: "Downtown Store",
    toStorageLotId: "3",
    toStorageLotName: "Showroom",
    userId: "2",
    userName: "Manager User",
    notes: "For display",
    createdAt: "2023-06-15T14:45:00Z",
  },
  {
    id: "3",
    wineId: "2",
    wineName: "Opus One",
    vintage: 2018,
    type: "in",
    quantity: 15,
    toLocationId: "1",
    toLocationName: "Main Warehouse",
    toStorageLotId: "1",
    toStorageLotName: "Section A",
    userId: "1",
    userName: "Admin User",
    notes: "New shipment",
    createdAt: "2023-07-10T10:20:00Z",
  },
  {
    id: "4",
    wineId: "3",
    wineName: "Penfolds Grange",
    vintage: 2017,
    type: "in",
    quantity: 12,
    toLocationId: "1",
    toLocationName: "Main Warehouse",
    toStorageLotId: "2",
    toStorageLotName: "Section B",
    userId: "2",
    userName: "Manager User",
    notes: "Special import",
    createdAt: "2023-07-22T11:10:00Z",
  },
  {
    id: "5",
    wineId: "1",
    wineName: "Château Margaux",
    vintage: 2015,
    type: "sale",
    quantity: 1,
    fromLocationId: "2",
    fromLocationName: "Downtown Store",
    fromStorageLotId: "3",
    fromStorageLotName: "Showroom",
    userId: "3",
    userName: "Staff User",
    notes: "Private collector purchase",
    createdAt: "2023-08-05T16:30:00Z",
  },
  {
    id: "6",
    wineId: "3",
    wineName: "Penfolds Grange",
    vintage: 2017,
    type: "transfer",
    quantity: 4,
    fromLocationId: "1",
    fromLocationName: "Main Warehouse",
    fromStorageLotId: "2",
    fromStorageLotName: "Section B",
    toLocationId: "3",
    toLocationName: "Cellar Storage",
    toStorageLotId: "5",
    toStorageLotName: "Aging Room",
    userId: "2",
    userName: "Manager User",
    notes: "For aging",
    createdAt: "2023-08-18T13:45:00Z",
  },
  {
    id: "7",
    wineId: "4",
    wineName: "Sassicaia",
    vintage: 2019,
    type: "in",
    quantity: 10,
    toLocationId: "1",
    toLocationName: "Main Warehouse",
    toStorageLotId: "2",
    toStorageLotName: "Section B",
    userId: "1",
    userName: "Admin User",
    notes: "Italian import",
    createdAt: "2023-09-05T09:15:00Z",
  },
  {
    id: "8",
    wineId: "5",
    wineName: "Screaming Eagle",
    vintage: 2016,
    type: "in",
    quantity: 3,
    toLocationId: "2",
    toLocationName: "Downtown Store",
    toStorageLotId: "4",
    toStorageLotName: "Reserve Room",
    userId: "1",
    userName: "Admin User",
    notes: "Rare allocation",
    createdAt: "2023-09-20T10:30:00Z",
  },
  {
    id: "9",
    wineId: "4",
    wineName: "Sassicaia",
    vintage: 2019,
    type: "transfer",
    quantity: 3,
    fromLocationId: "1",
    fromLocationName: "Main Warehouse",
    fromStorageLotId: "2",
    fromStorageLotName: "Section B",
    toLocationId: "2",
    toLocationName: "Downtown Store",
    toStorageLotId: "3",
    toStorageLotName: "Showroom",
    userId: "2",
    userName: "Manager User",
    notes: "For retail display",
    createdAt: "2023-10-05T15:20:00Z",
  },
  {
    id: "10",
    wineId: "4",
    wineName: "Sassicaia",
    vintage: 2019,
    type: "sale",
    quantity: 1,
    fromLocationId: "1",
    fromLocationName: "Main Warehouse",
    fromStorageLotId: "2",
    fromStorageLotName: "Section B",
    userId: "3",
    userName: "Staff User",
    notes: "Restaurant order",
    createdAt: "2023-10-15T14:10:00Z",
  },
]

// Mock Low Stock Alerts
export const mockLowStockAlerts: LowStockAlert[] = [
  { wineId: "4", wineName: "Sassicaia", vintage: 2019, totalQuantity: 9, threshold: 10 },
  { wineId: "5", wineName: "Screaming Eagle", vintage: 2016, totalQuantity: 3, threshold: 5 },
  { wineId: "6", wineName: "Domaine de la Romanée-Conti", vintage: 2018, totalQuantity: 4, threshold: 5 },
]

